on:
  push:
     branches:
       - master

name: ⏫ Copy content to REBEL

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Copy the 'post' folder
    - name: Push posts
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'cv-in-both-languages/CV_eng/Kreitmann_CV_eng.pdf' # Folder to copy
        destination_repo: 'ItsMeVictor/ItsMyCV/' # Target repo
        destination_folder: '' # Folder where to copy it
        user_email: 'victor.kreitmann@gmail.com'
        user_name: 'ItsMeVictor'
        commit_message: "AUTO: Syncing my CV"
        git_server: 'github.com'
